
name: Example usage

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      -
        uses: actions/checkout@v1

      -
        uses: SreeramPrabhakar/scp-action@master
        with:
          local: "./*"
          remote: "/home/tendu"
          host: ec2-34-230-11-27.compute-1.amazonaws.com
          port: 22
          user: tendu
          key: ${{ secrets.KEY }}
