name: scp files
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: copy file via ssh password
      uses:  SreeramPrabhakar/scp-action@master
      with:
        host: "ec2-34-230-11-27.compute-1.amazonaws.com"
        username: tendu
        password: tendu
        port: 22
        source: "tests/a.txt,tests/b.txt"
        target: "test"
